name: Driver Tests

on: [push]

jobs:
  drive_ios:

    runs-on: macos-latest

    strategy:
      matrix:
        device:
#          - "iPhone 8 (13.1)"
          - "iPhone 11 Pro Max (13.4.1)"

      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: List all simulators
      run: xcrun instruments -s
    # get UUID  simulator and boot a simulator on mac from  command line
    - name: Start Simulator
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: run test ${{ matrix.flavor }}
      run: "flutter drive --target=test_driver/app.dart"
